export const GRAPH_DATA = 'GRAPH_DATA';
export const SELECT_ROUND = 'SELECT_ROUND';
export const FILTER_ROUND_INDEX = 'FILTER_ROUND_INDEX';
export const SELECT_RANKING_BY = 'SELECT_RANKING_BY';
export const SELECT_ALIGN_BLOCKS = 'SELECT_ALIGN_BLOCKS';
export const RESET_GRAPH_VIEW = 'RESET_GRAPH_VIEW';
export const ROUND_PROC_BLOCK = 'ROUND_PROC_BLOCK';
